version: "3"

volumes:
    mysql_volume:

services:
    loghistory:
        build: ./
        restart: always
        ports:
            - 3000:3000
        environment:
            - TZ=Europe/Moscow
            - DB_USER=
            - DB_PASSWORD=
            - DB_NAME=
    
    mysqldb:
        image: mysql
        restart: always
        volumes:
            - mysql_volume:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=
            - MYSQL_DATABASE=
            - MYSQL_USER=
            - MYSQL_PASSWORD=