version: "3"

volumes:
    mysql_volume:
    ngnix_volume:
networks:
    app:

services:    
    mysqldb:
        image: mysql
        restart: always
        volumes:
            - mysql_volume:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
            - MYSQL_DATABASE=${DB_NAME}
            - MYSQL_USER=${DB_USER}
            - MYSQL_PASSWORD=${DB_PASSWORD}
        networks:
            - app
    loghistory:
        build: ./
        restart: always
        depends_on:
            - mysqldb
        ports:
            - 3000:3000
        environment:
            - TZ=Europe/Moscow
            - DB_HOST=mysqldb
            - DB_USER=
            - DB_PASSWORD=
            - DB_NAME=
            - DB_PORT=
            - DB_SYNCHRONIZE=
            - DB_ROOT_PASSWORD=
        networks:
            - app
    nginx:
        image: nginx
        restart: always
        ports:
            "80:80"
        volumes:
            - ngnix_volume:/etc/nginx/conf.d
        environment:
            - NGINX_HOST=
            - NGINX_PORT=80